### ISSUE TITLE
Dependencies to not-yet-released versions

### ISSUE THREAD

**Issue by axtimwalde** [fiji/pom-fiji#8]
The artifacts `Simple_Neurite_Tracer-3.0.1` and `Volume_Calculator-2.0.1` were not yet released.

**Comment by hinerm** [comment]
@iarganda are these ready for release now?

**Comment by iarganda** [comment]
@hinerm Yes!

**Comment by iarganda** [comment]
@hinerm I think I did something wrong trying to emulate how you do the releases. Please, have a look at this commit: https://github.com/fiji/Simple_Neurite_Tracer/commit/8492eb43cff719a063917b2f6b9570843c89f1d9
I've just realized you do the releases with the maven-release-plugin, so I guess what I did is not correct.

**Comment by ctrueden** [comment]
@iarganda You didn't do anything wrong. You have been using the [double-push to master method](http://imagej.net/Development_Lifecycle#Method_3:_Double_push_to_master), whereas @hinerm and I use the [Release-Version Jenkins job](http://imagej.net/Development_Lifecycle#Method_1:_Release-Version_Jenkins_job) for core ImageJ2 components, and the [release-version.sh script](http://imagej.net/Development_Lifecycle#Method_2:_release-version.sh) for Fiji components. All of these are currently valid methods for doing releases.

The double-push to master method does have some limitations and quirks, but until we have better release automation with Jenkins, is probably the easiest way for developers to cut Maven releases without needing any special credentials.

**Comment by iarganda** [comment]
@ctrueden I see! Since you told me we are migrating to an automatic release system, I didn't know any more if I should continue with my releasing method. In any case, both plugins are ready to be released, so just let me know if you require me to do anything. Thanks a lot!

**Comment by hinerm** [comment]
Fixed now. Thanks @iarganda ! :dancers:

**Comment by ctrueden** [comment]
> we are migrating to an automatic release system

Yep, still planned. But probably won't happen for a few more months. Don't worry—we'll definitely communicate loudly during such a transition.

**Comment by axtimwalde** [comment]
Thanks!
